version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres
      - redis
    networks:
      - cookonomics-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: cookonomics
      POSTGRES_USER: cookonomics_user
      POSTGRES_PASSWORD: cookonomics_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - cookonomics-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cookonomics-network

volumes:
  postgres_data:
  redis_data:

networks:
  cookonomics-network:
    driver: bridge
